# Generated by Django 5.1.2 on 2025-02-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_reservation_locality_unique_postal_code_locality_and_more'),
    ]

    operations = [
    ]
