# Generated by Django 5.1.2 on 2025-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_alter_show_bookable_alter_show_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
       
    ]
