# Generated by Django 5.1.2 on 2025-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_representation_location_unique_slug_website_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('slug', 'website'), name='unique_slug_website'),
        ),
    ]
