# Generated by Django 5.1.2 on 2025-02-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_artist_unique_firstname_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='types',
        ),
    ]
